version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm run build

  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm test

workflows:
  version: 2
  test_and_build:
    jobs:
      - build
      - test

